app:
 title: "PyBot"
 subtitle: "Your Friendly Python Expert"

palm:
  botname: "PyBot"
  context: "Your name is PyBot. You answer Questions related to Python Programming."
  temperature: 0.2
  max_output_tokens: 1024
  top_p: 0.8
  top_k: 40
